### ISSUE TITLE
Bug: MockKAgentException when creating a mock on >= Api level 28 due to missing 64 binaries

### ISSUE THREAD

**Issue by jtrollkarl** [mockk/mockk#297]
### Expected Behavior

Expecting mocked instances to be initialised correctly.

### Current Behavior

Currently, whenever a mock of a class is created a MockKAgentException is thrown (see stacktrace below) on api level 28 or greater. I don't seem to be having any issues on lower API levels.

#### Steps to Reproduce

1. Create a test case containing code to create a mock
2. Run test

#### Context

* MockK version: 1.9.3
* OS: >= API level 28
* Kotlin version: 1.3.11
* JDK version: 8
* JUnit version: 4.12
* Type of test: instrumented test

#### Stack trace

```
Caused by: io.mockk.proxy.MockKAgentException: MockK could not self-attach a jvmti agent to the current VM. This feature is required for inline mocking.
This error occured due to an I/O error during the creation of this agent: java.io.IOException: No such file or directory

Potentially, the current VM does not support the jvmti API correctly
at io.mockk.proxy.android.AndroidMockKAgentFactory.init(AndroidMockKAgentFactory.kt:63)
at io.mockk.impl.JvmMockKGateway.<init>(JvmMockKGateway.kt:46)
at io.mockk.impl.JvmMockKGateway.<clinit>(JvmMockKGateway.kt:172)
... 33 more
Caused by: java.io.IOException: No such file or directory
at java.io.UnixFileSystem.createFileExclusively0(Native Method)
at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
at java.io.File.createTempFile(File.java:2018)
at java.io.File.createTempFile(File.java:2064)
at io.mockk.proxy.android.JvmtiAgent.appendToBootstrapClassLoaderSearch(JvmtiAgent.kt:53)
at io.mockk.proxy.android.AndroidMockKAgentFactory.init(AndroidMockKAgentFactory.kt:48)
... 35 more
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    androidTestImplementation "io.mockk:mockk-android:1.9.3"
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
object MockHelper {
    fun mockIsEnabled(enabled: Boolean = false) {

        val mock: LocationChecker = mockk(relaxed = true) //failure here

        val component = DaggerTestAppComponent
            .builder()
            .testModule(TestModule(locationChecker = mock))
            .build()

        val application = Application.getApplication(InstrumentationRegistry.getTargetContext())
        application.appComponent = component
    }
}

@RunWith(AndroidJUnit4::class)
class ScreenTest : BaseUITest() {

    @Before
    fun setUp() {
        MockHelper.mockIsEnabled(true)
    }
    
}

// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by ryansgot** [comment]
@jtrollkarl I'm running into this, too. And I think I have a root cause. The rest of the exception message complains about not being able to find `libmockkjvmtiagent.so`. As you can see in this screenshot (apkAnalyzer of my app's test apk), the x86_64 and arm64-v8a binaries for `libmockkjvmtiagent.so` do not exist:

<img width="1170" alt="Screen Shot 2019-07-19 at 2 47 48 PM" src="https://user-images.githubusercontent.com/4745799/61567805-b816c780-aa35-11e9-952c-feb8761d6f8a.png">

> I don't seem to be having any issues on lower API levels.

Same here. That seems to be due to this `SDK_INT` check: https://github.com/mockk/mockk/blob/fdb6839b316bfee571a387852c3de7448a6eb64b/agent/android/src/main/kotlin/io/mockk/proxy/android/AndroidMockKAgentFactory.kt#L32

I don't see anywhere else in mockk's source that this particular exception can be thrown. 

An additional contributing factor why you're not seeing this on other API levels is _probably_ that you're loading a x86_64 or arm64-v8a in your tests on a device that is x86_64 or arm64-v8a hardware. _Conveniently_, x86_64 platform images only seem to be available from API 28 onwards on the google repository:

``` 
$ ./tools/bin/sdkmanager "system-images;android-27;google_apis;x86_64"
Warning: Failed to find package system-images;android-27;google_apis;x86_64     
Error: Package path is not valid. Valid system image paths are:ository...       
system-images;android-28;google_apis;x86
system-images;android-26;google_apis_playstore;x86
system-images;android-18;google_apis;x86
system-images;android-25;google_apis;x86
system-images;android-25;google_apis_playstore;x86
system-images;android-26;google_apis;x86
system-images;android-28;google_apis;x86_64
system-images;android-23;google_apis;x86
system-images;android-27;google_apis;x86
system-images;android-19;google_apis;x86
system-images;android-22;google_apis;x86
system-images;android-21;default;armeabi-v7a
system-images;android-21;google_apis;x86
system-images;android-22;default;x86
null
```

So you may see this if you test on emulators--since those emulators are 32-bit, they'd be loading the 32-bit versions of your shared objects and the 32-bit version of `libmockkjvmtiagent.so`, which exists.

So my suggestion to work around this for now is to exclude the 64-bit versions of the shared objects that you load from your test apks (which I realize defeats the point of testing them in the first place). You'd like to test the 64-bit versions to make it as close to production as possible.

Likely, the motivation for including the 64-bit binaries is the Google Play requirement to include 64-bit native binaries by August 1st. That is the motivation for me. So it would be nice to see a 64-bit version of `libmockkjvmtiagent.so`. 

@oleksiyp Do you think the x86_64 and arm64-v8a architectures will be supported soon?

**Comment by PaulWoitaschek** [comment]
Add an important label! This makes mockk unusable on android 10.

**Comment by PaulWoitaschek** [comment]
@oleksiyp Can you please re-open this issue?

**Comment by mickjjfs** [comment]
I also have this problem after upgrading to Android Studio 3.6 Beta 2 (from 3.6 Beta 1 which was working)
### Context
* MockK version: 1.9.3
* OS: >= API level 28
* Kotlin version: 1.3.11
* JDK version: 8
* JUnit version: 4.12
* Type of test: instrumented test
* min_sdk = 26
* target_sdk = 29 or 28 (my project won't compile on anything less)
* Android Emulator API version 26, 27, or 28

I will try to rollback Android Studio updates

**Comment by mickjjfs** [comment]
Nope that did not work

* restored Android Studio 3.6 Beta 1 from backup
* restored ~/Android from backup
* deleted ~/.gradle/caches and rebuild 

Where should this file reside? `libmockkjvmtiagent.so`

I still get 
     Caused by: io.mockk.proxy.MockKAgentException: MockK could not self-attach a jvmti agent to the current VM. This feature is required for inline mocking.
    This error occured due to an I/O error during the creation of this agent: java.io.IOException: Unable to dlopen libmockkjvmtiagent.so: dlopen failed: library "libmockkjvmtiagent.so" not found
    
    Potentially, the current VM does not support the jvmti API correctly
        at io.mockk.proxy.android.AndroidMockKAgentFactory.init(AndroidMockKAgentFactory.kt:63)
        at io.mockk.impl.JvmMockKGateway.<init>(JvmMockKGateway.kt:46)
        at io.mockk.impl.JvmMockKGateway.<clinit>(JvmMockKGateway.kt:172)
        	... 29 more
     Caused by: java.io.IOException: Unable to dlopen libmockkjvmtiagent.so: dlopen failed: library "libmockkjvmtiagent.so" not found
        at dalvik.system.VMDebug.nativeAttachAgent(Native Method)
        at dalvik.system.VMDebug.attachAgent(VMDebug.java:570)
        at android.os.Debug.attachJvmtiAgent(Debug.java:2481)
        at io.mockk.proxy.android.JvmtiAgent.<init>(JvmtiAgent.kt:46)
        at io.mockk.proxy.android.AndroidMockKAgentFactory.init(AndroidMockKAgentFactory.kt:36)
        	... 31 more
    ----- end exception -----

**Comment by mickjjfs** [comment]
The last thing I also upgraded was the Android Gradle Plugin - from 3.5.1 to 3.6.0-beta01

Reverting back to Android Gradle Plugin 3.5.1 makes mockk work again!
Also works with Android Studio 3.6 Beta 2

## So Android Gradle Plugin 3.6.0-beta01 caused this problem for me - stick to 3.5.1

Hope that helps

**Comment by koehleru** [comment]
I also have this problem after upgrading from min_sdk 21 to min_sdk 23.
It happens only in the x64 Emulator

### **Context**
MockK version: 1.10.0
OS: >= API level 28
Kotlin version: 1.3.72
JDK version: 8
JUnit version: 4.12
Type of test: instrumented test
min_sdk = 23
target_sdk = 29 
Android Emulator API version  28 

`
Potentially, the current VM does not support the jvmti API correctly
     at io.mockk.proxy.android.AndroidMockKAgentFactory.init(AndroidMockKAgentFactory.kt:65)
     at io.mockk.impl.JvmMockKGateway.<init>(JvmMockKGateway.kt:46)
     at io.mockk.impl.JvmMockKGateway.<clinit>(JvmMockKGateway.kt:172)
... 29 more
Caused by: java.io.IOException: Unable to dlopen libmockkjvmtiagent.so: dlopen failed: library "libmockkjvmtiagent.so" not found
     at dalvik.system.VMDebug.nativeAttachAgent(Native Method)
     at dalvik.system.VMDebug.attachAgent(VMDebug.java:526)
     at android.os.Debug.attachJvmtiAgent(Debug.java:2398)
     at io.mockk.proxy.android.JvmtiAgent.<init>(JvmtiAgent.kt:48)
     at io.mockk.proxy.android.AndroidMockKAgentFactory.init(AndroidMockKAgentFactory.kt:38)
... 31 more
`

**Comment by dri94** [comment]
Same issue here

MockK version: 1.10.0
OS: >= API level 28
Kotlin version: 1.3.71
JDK version: 8
JUnit version: 4.12
Type of test: instrumented test
min_sdk = 26
target_sdk = 29
Android Emulator API version 29

**Comment by oleksiyp** [comment]
@dri94 I spent some time trying to fix this issue. Unfortunately, I didn't find easy way to fix it.

**Comment by dri94** [comment]
@oleksiyp I'm confused, I just now see you moved it to fixed a couple of days ago, is it not fixed? Either way, thanks for all the hard work. I wish i was more adept to help you with this mocking library as it is truly a great one.

**Comment by oleksiyp** [comment]
it was labeled by mistake

**Comment by NitroG42** [comment]
It is also happening on x86 image, not only x86_64. I'm not sure what we can do

**Comment by DonJogi** [comment]
Some for me, unfortunately. I just updated the Android Gradle plugin from 3.5.1 to 3.6.3 in my Android project:
`implementation("com.android.tools.build:gradle:3.6.3")`

Now my instrumented tests fail. Reverting to 3.5.1 seems like the only option so far.

I also tried `android.useNewApkCreator=false` and ` android:extractNativeLibs="true"` out of lack of ideas, but with no success.

**Comment by olegosipenko** [comment]
Tried updating Android Gradle Plugin to `4.0.0` and the issue is still present resulting in failing instrumented tests

**Comment by DonJogi** [comment]
I tried it again and found that I put the flag "extractNativeLibs" into the main manifest instead of the androidTest manifest which has no effect.

It works if you put an AndroidManifest.xml into your src/androidTest folder with this content:
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.package">

    <application android:extractNativeLibs="true" />
</manifest>
```

Of course this seems to only be a workaround for that change, however, but at least it works for now:
https://developer.android.com/studio/releases/gradle-plugin#extractNativeLibs

**Comment by perricesoft** [comment]
Any update on this issue?

**Comment by cristan** [comment]
Weird: this issue was reported with MockK version: 1.9.3, but I don't get this error with this version, but I do get it with 1.10.2

**Comment by kshdreams** [comment]
I have a same problem.

MockK version: 1.10.2
OS: >= API level 28
Kotlin version: 1.4.10
JDK version: 8
JUnit version: 4.12
Type of test: instrumented test
min_sdk = 28
target_sdk = 29
Android Emulator API version 29

Caused by: io.mockk.proxy.MockKAgentException: MockK could not self-attach a jvmti agent to the current VM. This feature is required for inline mocking.
This error occured due to an I/O error during the creation of this agent: java.io.IOException: Unable to dlopen libmockkjvmtiagent.so: dlopen failed: library "libmockkjvmtiagent.so" not found

**Comment by giancarlogatti** [comment]
@DonJogi This didn't work for me, I even did:

SourceSets {
        androidTest.manifest.srcFile "src/androidTest/AndroidManifest.xml"
    }

That did not work either. Even changed the test build type to debug and put the manifest in the debug package. Did not work. The same error. Am I missing something?

**Comment by giancarlogatti** [comment]
Also I'd like to say moving down to Gradle 3.5.1 is a crazy solution, can't even use viewbinding with that version

**Comment by epicstar** [comment]
> Weird: this issue was reported with MockK version: 1.9.3, but I don't get this error with this version, but I do get it with 1.10.2

I have this same exact issue. I'm using mockk 1.9.3 until 1.10.x is fixed.

**Comment by shalbert94** [comment]
Decided to pull `androidTestImplementation "io.mockk:mockk-android:$mockk_version"` from instrumented tests because there doesn't seem to be to a worthwhile solution. Definitely will proceed to use Mockk in JVM tests

**Comment by drindt** [comment]
I have the same issue and i found this on a x86_64 device:
`Accessing hidden method Ldalvik/system/VMRuntime;->setHiddenApiExemptions([Ljava/lang/String;)V (blacklist,core-platform-api, reflection, denied)`

Therefore is another call which is allowed:
`Accessing hidden method Ldalvik/system/VMRuntime;->getRuntime()Ldalvik/system/VMRuntime; (greylist,core-platform-api, reflection, allowed)`

It seems here is another blocker around this.

**Comment by TonyTranHaltiner** [comment]
Are there any updates on this issue? Was anyone able to get it working?

**Comment by FranckRJ** [comment]
@oleksiyp The issue is still there on 1.10.5, but it's labeled as fixed, why ?

**Comment by treitter** [comment]
I can also still reproduce this bug on 1.10.5 and 1.10.6 (and 1.9.3) with several versions of the Android Gradle Plugin, running against various API levels (27, 28, 29, 30), both x86 and x86_64 images, adding `<application android:extractNativeLibs="true" />` to my `androidTest` `AndroidManifest.xml`, etc. None of these work-arounds or dependency versions seem to solve this problem for me.

Any other suggestions would be greatly appreciated!

**Comment by reid-mcpherson** [comment]
Still seeing this issue on 1.10.6.

**Comment by knthmn** [comment]
So I had two projects, one had this exact issue but the other one ran mockk just fine. I spent an hour trying to figure out what differs between the projects. Here is what I found.

In the project that mockk was working, I had the following dependencies from this library https://github.com/wseemann/FFmpegMediaMetadataRetriever
```
implementation 'com.github.wseemann:FFmpegMediaMetadataRetriever-core:1.0.15'
implementation 'com.github.wseemann:FFmpegMediaMetadataRetriever-native:1.0.15'
```

I added this to my other project, and also used it in a test ( `val foo= FFmpegMediaMetadataRetriever()`), now mockk works.

My versions:
AGP: 7.0.0-alpha10
JDK: 13
Kotlin: 1.4.31
compile/targetSdk: 30, minSdk: 23

I have no idea why this would be the case but I guess because FFmpegMediaMetadataRetriever uses some native libraries. Hopefully this helps someone.

**Comment by edgarmiro** [comment]
> So I had two projects, one had this exact issue but the other one ran mockk just fine. I spent an hour trying to figure out what differs between the projects. Here is what I found.
> 
> In the project that mockk was working, I had the following dependencies from this library https://github.com/wseemann/FFmpegMediaMetadataRetriever
> 
> ```
> implementation 'com.github.wseemann:FFmpegMediaMetadataRetriever-core:1.0.15'
> implementation 'com.github.wseemann:FFmpegMediaMetadataRetriever-native:1.0.15'
> ```
> 
> I added this to my other project, and also used it in a test ( `val foo= FFmpegMediaMetadataRetriever()`), now mockk works.
> 
> My versions:
> AGP: 7.0.0-alpha10
> JDK: 13
> Kotlin: 1.4.31
> compile/targetSdk: 30, minSdk: 23
> 
> I have no idea why this would be the case but I guess because FFmpegMediaMetadataRetriever uses some native libraries. Hopefully this helps someone.

It works only with:
```
implementation 'com.github.wseemann:FFmpegMediaMetadataRetriever-native:1.0.15'
```

Thanks! And we expect a workaround for this bug as soon as possible.

**Comment by knthmn** [comment]
> 
> It works only with:
> 
> ```
> implementation 'com.github.wseemann:FFmpegMediaMetadataRetriever-native:1.0.15'
> ```
> 
> Thanks! And we expect a workaround for this bug as soon as possible.

I can confirm that. Also it appears that doing `val foo= FFmpegMediaMetadataRetriever()` is not required, however sometimes a `gradle clean` is needed to summon the spirits to make mockk work 🤷

**Comment by treitter** [comment]
Including `FFmegMediaMetadataRetriever-native` worked around this bug for me as well. I looked at that project's `build.gradle` files and narrowed it down so all I need to add to my `build.gradle` to avoid this bug is:

`androidTestImplementation "androidx.annotation:annotation:1.1.0"`

I'm not sure exactly why it works but I'm a lot more comfortable including this than `FFmegMediaMetadataRetriever-native`.

So, maybe MockK actually depends on `androidx.annotation:annotation` but the dependency doesn't gets passed along correctly?

**Comment by knthmn** [comment]
@treitter I cannot get it to work with only `androidx.annotation:annotation:1.1.0`

**Comment by treitter** [comment]
@knthmn Sorry, it seemed that I isolated a fix down to that line but it must somehow have been a coincidence. I later tracked down a bug in my test environment so I'm not sure I'm actually hitting this bug anymore. I'll see once I've got substantive tests that use MockK running reliably.

**Comment by knthmn** [comment]
So I then included `FFmegMediaMetadataRetriever-native` again and it didn't work until I stashed my changes, switched branches back and forward in git. Whatever is happening it is extremely brittle.

I cannot confirm if `androidx.annotation:annotation:1.1.0` actually works, can't be bothered to test it now.

**Comment by les-kasa-1010** [comment]
I used v1.11.0, and same issue happened.

DonJogi's workaround(https://github.com/mockk/mockk/issues/297#issuecomment-641361770) worked for me.

**Comment by wwbakker** [comment]
We had a similar problem, namely androidTest failing with the following error:

```
java.lang.ExceptionInInitializerError
	at our.app.SuccessFragmentTest.<init>(SuccessFragmentTest.kt:54)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2205)
Caused by: io.mockk.proxy.MockKAgentException: MockK could not self-attach a jvmti agent to the current VM. This feature is required for inline mocking.
This error occured due to an I/O error during the creation of this agent: java.io.IOException: Native-bridge agents unsupported: libmockkjvmtiagent.so

Potentially, the current VM does not support the jvmti API correctly
	at io.mockk.proxy.android.AndroidMockKAgentFactory.init(AndroidMockKAgentFactory.kt:67)
	at io.mockk.impl.JvmMockKGateway.<init>(JvmMockKGateway.kt:46)
	at io.mockk.impl.JvmMockKGateway.<clinit>(JvmMockKGateway.kt:173)
	... 28 more
Caused by: java.io.IOException: Native-bridge agents unsupported: libmockkjvmtiagent.so
	at dalvik.system.VMDebug.nativeAttachAgent(Native Method)
	at dalvik.system.VMDebug.attachAgent(VMDebug.java:572)
	at android.os.Debug.attachJvmtiAgent(Debug.java:2563)
	at io.mockk.proxy.android.JvmtiAgent.<init>(JvmtiAgent.kt:48)
	at io.mockk.proxy.android.AndroidMockKAgentFactory.init(AndroidMockKAgentFactory.kt:40)
	... 30 more
```

This was solved by **removing** the following from our `build.gradle.kts` file:
```
android {
    defaultConfig {
        ndk {
            abiFilters("armeabi-v7a", "arm64-v8a")
        }
   }
}
```

This might not be an issue with this library, but when I googled our issue, this issue came up first. Hopefully this comment will help others in the future.

**Comment by stetro** [comment]
I still see this issue in my project as well, all above described possible solutions didn't work

**Comment by npaz** [comment]
Same here...
I tried to make some instrumented unit tests and unfortunately I get stuck in the same problem 😞

**Comment by afrueh** [comment]
I had the same issue in our project while upgrading to the latest gradle version.

At first the https://github.com/mockk/mockk/issues/297#issuecomment-641361770 did not work for us.

By chance I found this warning when using the custom Manifest (https://github.com/mockk/mockk/issues/297#issuecomment-641361770) on the "old" gradle version:
`PackagingOptions.jniLibs.useLegacyPackaging should be set to true because android:extractNativeLibs is set to "true" in AndroidManifest.xml.`

Enabling the PackagingOption within the Android testOptions then finally solved the issue for me:
```
android {
  testOptions {
      packagingOptions {
          jniLibs {
              useLegacyPackaging true
          }
      }
   }
}
```

Maybe this workaround helps others :)

**Comment by hafiedh** [comment]
@afrueh this work for me, thank

**Comment by ggeetha** [comment]
@afrueh Ur workaround solved my issue as well. Thanks much.

**Comment by rusvaitamas** [comment]
@afrueh Had the same issue, and your solution fixed it. Thank you.

**Comment by kjaspinder** [comment]
I am still facing this with and workarounds mentioned above including https://github.com/mockk/mockk/issues/297#issuecomment-901924678 and not working.

**Comment by BorisNavvis** [comment]
Still have the same issue with version 1.12.3
```
Caused by: io.mockk.proxy.MockKAgentException: MockK could not self-attach a jvmti agent to the current VM. This feature is required for inline mocking.
This error occured due to an I/O error during the creation of this agent: java.io.IOException: Native-bridge agents unsupported: libmockkjvmtiagent.so
```

**Comment by AndreiKud** [comment]
@kjaspinder switched from `1.12.4` to `1.12.3` after seeing [this comment](https://github.com/mockk/mockk/issues/819#issuecomment-1131879106). Worked for me. Non of the previous workarounds did the trick either.

**Comment by AnandaDwiprayoga** [comment]
@AndreiKud yeah change the version to 1.12.3 did the trick for me

**Comment by josh-bartz** [comment]
I'm seeing this issue on:
mockk: 1.13.5
JDK: 9
Kotlin: 1.6.0
OS: 28+
JUnit 4.13.2

But it's only happening for instrumented tests on android-library modules. The same config works fine for the app module.
