### ISSUE TITLE
ClassCastException when using relaxed mock of generic type

### ISSUE THREAD

**Issue by rdgoite** [mockk/mockk#321]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Description

I might have run into a MockK limitation trying to use relaxed mock of a generic type (particularly Spring's `JpaRepository`). When using such mock object, my test throws a `ClassCastException` at the point where the test code calls the method of the mock object that returns an object using the type parameter.

For example, if have the following types,

```
interface BaseRepository<T> {
    fun save(obj: T): T
}

interface BookRepository: BaseRepository<Book>
```

and I declare a relaxed mock for `BookRepository`, the test throws a `ClassCastException` during the invocation of `save(book)`.

#### Steps to Reproduce

I have prepared a [demo code base](https://github.com/rdgoite/demo-mockk-relaxed-mock) to illustrate this issue. Please check the last 3-4 commits as I experimented a bit to confirm that this issue doesn't only affect Spring's `JpaRepository` but in general, any type (interface) with similar declaration.

**Comment by robstoll** [comment]
ame problem here (mockk 1.9.3). Small example code to reproduce the problem:
```
interface BaseRepository<T> {
    fun save(obj: T): T
}

interface IntRepository: BaseRepository<Int>

fun main(args: Array<String>) {
    val a = mockk<IntRepository>(relaxed = true)
    a.save(1)
}
```
Results in:
```
Exception in thread "main" java.lang.ClassCastException: java.lang.Object cannot be cast to java.lang.Integer
```

**Comment by mimozell** [comment]
I am experiencing the same issue. I am trying to mock the following function:

`inline fun <reified T, reified U> post(uri: String, body: T): U? = webClient
        .post()
        .uri(uri)
        .body(Mono.just(body), T::class.java)
        .retrieve()
        .bodyToMono(U::class.java)
        .block()`

like this:

`every { httpClient.post<Map<String, Any>, User>(any(), hashMapOf()) } returns createUser(email = email)`

but get the same error as above:
`java.lang.Object cannot be cast to User`. I am using version 1.9.3 of mockk and a relaxed mock of the httpClient.

Oddly enough, mocking this function works fine:
`inline fun <reified T> getMono(uri: String): Mono<T> = webClient
        .get()
        .uri(uri)
        .retrieve()
        .bodyToMono(T::class.java)
        .block()`

Is there any update on this?

**Comment by nuhkoca** [comment]
I am facing the same issue. I am using a result wrapper for my network models.

```
sealed class Result<out R> {
    data class Success<out T>(val data: T) : Result<T>()
    data class Error(val exception: Failure) : Result<Nothing>()
}
```

However I am getting;

`java.lang.ClassCastException: java.lang.Object cannot be cast to mypath.data.MyResponse`

**Comment by oleksiyp** [comment]
Try to use `hint`. check docs

пт, 6 мар. 2020 г., 10:54 Nuh Koca <notifications@github.com>:

**Comment by nuhkoca** [comment]
@oleksiyp thanks it seems useful however I am having one question.

Because of this generic type, whenever I want to access a `val` of my data class, I am getting;

`io.mockk.MockKException: no answer found for: MyResponse(myResponse#2).getMyVal()
`
How can I fix this with `hint`? I am using it like;

```
coEvery {
            service.fetchPolygons(
                any(),
                capture(maxSpeedSlot),
                any(),
                any()
            ).hint(Result::class)
        } answers {
            myResponse
        }
```

but it didn't work. Thanks!

**Comment by oleksiyp** [comment]
Hint should be before call

пт, 6 мар. 2020 г., 11:26 Nuh Koca <notifications@github.com>:

**Comment by nuhkoca** [comment]
Ok, it is working. So do I have to use `hint` per assertion? I mean I'd like to assert 3 conditions so that I need to create `coEvery` per condition, right?

**Comment by yavski** [comment]
> I am facing the same issue. I am using a `Result` wrapper for my network models.
> 
> ```
> sealed class Result<out R> {
>     data class Success<out T>(val data: T) : Result<T>()
>     data class Error(val exception: Failure) : Result<Nothing>()
> }
> ```
> 
> However, I am getting;
> 
> `java.lang.ClassCastException: java.lang.Object cannot be cast to mypath.data.MyResponse`

hey @nuhkoca did you manage to resolve that issue?

**Comment by nuhkoca** [comment]
@yavski I fixed this switching to `Coroutines` and wrapping `Result` in `Flow`. Then I am able to easily test my `flow` with cashapp's turbine.

https://github.com/cashapp/turbine

**Comment by liquidjoo** [comment]
I solved it as below
```every { repository.save<ReturnTypecClass>(any()) } returns ReturnTypeClass```

**Comment by gerardoepitacio** [comment]
I am wrong assuming that the intention when we use `mockk(relaxed = true)` is to avoid writing a default answer where every call is done?

**Comment by marcosalis** [comment]
@oleksiyp is there anything we can do to get a workaround for this by any chance?
On large codebases this is causing hundreds of tests failures which would be really hard to fix one by one with `hint`.
Thank you in advance for looking into it! 🙏

**Comment by egek92** [comment]
any update on this??

**Comment by konaire** [comment]
Hey guys, it's blocking me and my team from updating to Android Studio 4.2 since it requires Java 11 and our codebase has a lot of tests in mockk that throw this exception on Java 11. Could you give an estimate when it's going to be fixed?

**Comment by jstarzynski** [comment]
Hello, any update on this? 🙏

**Comment by diegocunhawarren** [comment]
Hey guys, a quick light on this issue

I was facing the problem when I was writing unit tests where one of mocked parameters was called at my ViewModel class.

I fixed this by creating mocks with `every/coEvery` of the mocked object functions that were called at the time of the crash.

**Comment by Jelledb** [comment]
As it is quite common to test with the JpaRepository pattern, this issue is quite impactful.

**Comment by lebedynskyi** [comment]
Still have this issue even if relaxed == false. 
But now i have Result<Boolean> instead of Result<MyClass>

**Comment by fdhuseynov** [comment]
Not able to mock repository beans, get this error with `save` calls.
Tried to use `hint` and `relaxed`, still same problem.

**Comment by DasOhmoff** [comment]
I also have the same issue. It's very unfortunate.

**Comment by martinlacorrona** [comment]
Any update here?

**Comment by mbalajee** [comment]
Would love to know the rationale behind this implementation, if this is intentional in mockk.

I get ClassCastException when mocking a function from parent interface.  In the below code, `findByName` is in `GrandParent` interface and requires the use of `hint` (which is kinda annoying).  If i move the function to `Parent` interface then it works without `hint`

Minimum reproducible code:

Below code requires the usage of `hint` (same code works with `mockito`)
```
interface Human<T>
class HumanImpl: Human<String>

interface GrandParent<T> {
    fun findByName(): T
}
interface Parent<T: Human<String>>: GrandParent<T>

class HintTest {

    private val mockRemoteDao = mockk<Parent<HumanImpl>>()

    @Test
    fun testHint() {
        every { mockRemoteDao.findByName() } returns HumanImpl() // =>  Class cast exception

        every { mockRemoteDao.hint(Human::class).findByName() } returns HumanImpl() //  => Class cast exception

        every { mockRemoteDao.hint(HumanImpl::class).findByName() } returns HumanImpl() //  => Works
    }
}
```
