### ISSUE TITLE
Unresolved reference: mockk

### ISSUE THREAD

**Issue by gchristov** [mockk/mockk#602]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

Expecting to be able to declare and run a statement like this `mockk<Repository>()`.

### Current Behavior

`Task :appShared:compileDebugUnitTestKotlinAndroid FAILED` with `Unresolved reference: mockk`. Android Studio actually shows no errors on the UI and is able to resolve the reference to mockk but when I run my tests it fails with the error above. I have tried invalidating caches and restarting AS, as well as reimporting Gradle project and cleaning the dependencies. 

#### Steps to Reproduce

1. Create simple Kotlin Multiplatform project with iOS/Android support and add some shared code
2. Write unit test for shared code using mockk library
3. Use mockk API to build a mock of a class and test it with `verify()`

#### Context

* Android Studio version: 4.2 RC 1
* MockK version: 1.11.0
* OS: MacOS Catalina 10.15.7
* Kotlin version: 1.4.32
* Gradle Plugin version: 4.2.0-rc01
* Gradle version: 6.7.1
* Type of test: unit test

#### Failure Logs

```
> Task :appShared:compileDebugUnitTestKotlinAndroid FAILED
e: /Users/georgi/Documents/Workspace/Android/Studio/guardian-news-kmm/appShared/src/commonTest/kotlin/com/gchristov/guardiannews/appShared/repository/model/ArticleDecoratorTest.kt: (4, 17): Unresolved reference: mockk
```

#### Minimal reproducible code (the gist of this issue)

```
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
kotlin {
  sourceSets {
    val commonTest by getting {
        dependencies {
            implementation(kotlin("test-common"))
            implementation(kotlin("test-annotations-common"))
            implementation("io.mockk:mockk-common:1.11.0")
        }
    }
  }
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package com.gchristov.guardiannews.appShared.repository.model

import com.gchristov.guardiannews.appShared.repository.Repository
import io.mockk.mockk
import kotlinx.datetime.Clock
import kotlin.test.Test

class ArticleDecoratorTest {

    private val repository = mockk<Repository>()

    @Test
    fun test_decorate() {
        val mapped = ArticleDecorator().decorate(getArticle(), repository)
        verify{ repository.favouriteTimestamp(any()) }
        assertNotNull(mapped)
    }

    private fun getArticle(): Article { ... }
}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by Raibaz** [comment]
I think changing your `io.mockk:mockk-common` dependency to `io.mockk:mockk` should fix the issue.

Let me know if it works.

**Comment by gchristov** [comment]
I replaced with this `implementation("io.mockk:mockk:1.11.0")` and now there's a different issue:

```
Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' option
```

I also tried adding both dependencies and still getting the same issue. Is there some other config for multiplatform that I've missed?

**Comment by Raibaz** [comment]
What Java version are you using?

You can change the target version with

```
compileKotlin {
        kotlinOptions.jvmTarget = <your version number>
    }
    compileTestKotlin {
        kotlinOptions.jvmTarget = <your version number>
    }
```

In your build.gradle.

Mockk requires at least 1.8, as you may have guessed by the error message.

**Comment by gchristov** [comment]
Adding
```
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}
```
together with `implementation("io.mockk:mockk:1.11.0")` to my build.gradle.kts has fixed the issue indeed. Thanks!
