### ISSUE TITLE
java.lang.InstantiationError when upgrading to Kotlin 1.7

### ISSUE THREAD

**Issue by hantsy** [mockk/mockk#832]
Java 17 + Kotlin 1.7 + Mockk 1.12.4/Spring Mockk 3.1.1

```bash 
java.lang.InstantiationError: com.example.demo.UpdateAccountResult
    at jdk.internal.reflect.GeneratedSerializationConstructorAccessor18.newInstance(Unknown Source)
    at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
    at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:48)
```

It occurred whens using `coEvery{}` to do some stub, which returns a `UpdateAccountResult.Success()`.

Here `UpdateAccountResult` is a `sealed class`, it has some detailed result subclass/sub data classes.

And `UpdateAccountResult` extends from a base abstract class like this.

```kotlin 
abstract class ApiBaseResult {
    @field:JsonProperty("SC")
    val statusCode: String? = null

    @field:JsonProperty("EC")
    val errorCode: String? = null

    @field:JsonProperty("EM")
    val errorMessage: String? = null
}
``` 

These codes are working well with **Kotlin 1.6.21**.

**Comment by cmdjulian** [comment]
I can confirm the problem as were having it too

**Comment by hantsy** [comment]
@ygaller it seems related to `sealed class`.

**Comment by pkgonan** [comment]
I have a same problem. 

1. coEvery { any() } -> java.lang.InstantiationError !
2. sealed interface -> mockk(relaxed = true) -> io.mockk.MockKException: Can't instantiate proxy for class !

**Comment by DanielCecvarek** [comment]
Meaningless bump. This is most definitely related to `sealed class`. Occurs with every `every { ... }` and with Kotlin `1.7.0` and mocck `1.12.4`

**Comment by danielrehmann** [comment]
We encounter the same issue with sealed classes and interfaces with version `1.12.4` when we try to upgrade to Kotlin `1.7.0`. Happens in the `coEvery` `every`, `verify` and `coVerify` blocks throwing a `java.lang.InstantiationError`.

**Comment by hantsy** [comment]
Any update for this issue, is there any workaround?

**Comment by ThanksForAllTheFish** [comment]
Thanks for the suggestion, here a reproduction project: https://github.com/ThanksForAllTheFish/mockk832

**Comment by QUEnDo** [comment]
Same to me...

**Comment by Raibaz** [comment]
Apparently something changed with sealed classes in 1.7.

However, I couldn't find anything in the release notes: the only mention of sealed classes is that non-exhaustive sealed hierarchies now trigger an error rather than a warning.

**Comment by cliffred** [comment]
> Apparently something changed with sealed classes in 1.7.
> 
> However, I couldn't find anything in the release notes: the only mention of sealed classes is that non-exhaustive sealed hierarchies now trigger an error rather than a warning.

Apparently Kotlin 1.7 in combination with Java 17 uses Java sealed classes. 

I compiled the following code with Kotlin 1.6 and 1.7 and then decompiled.
```kotlin
sealed class Foo
class Bar : Foo()
```

Kotlin 1.7 decompiled:
```java
public abstract sealed class Foo permits Bar {
   private Foo() {
   }

   // $FF: synthetic method
   public Foo(DefaultConstructorMarker $constructor_marker) {
      this();
   }
}
```

Kotlin 1.6 decompiled:
```java
public abstract class Foo {
   private Foo() {
   }

   // $FF: synthetic method
   public Foo(DefaultConstructorMarker $constructor_marker) {
      this();
   }
}
```

**Comment by eygraber** [comment]
Right, Java 17 added a sealed class feature, and I guess Kotlin is supporting that in the bytecode for Kotlin sealed classes when compiling with Java 17.

**Comment by huginr** [comment]
I have worked around it by mocking a specific implementation type instead of the sealed class itself. However that is not ideal.

Is there any news if mocking sealed classes and interfaces will be possible again later?

**Comment by cliffred** [comment]
I've locally tried a to solve it in a hacky way to see if it would work, by adding an extra if statement to https://github.com/mockk/mockk/blob/02a49b2f3639e066ff96d35a160bf301fe0bbb00/agent/jvm/src/main/kotlin/io/mockk/proxy/jvm/ProxyMaker.kt#L98

```kotlin
runCatching {
    if (clazz.isSealed) {
        return subclass(clazz.permittedSubclasses.first() as Class<T>, interfaces)
    }
}
```

This does work, but arbitrarily picking the first permitted sub class feels like an ugly hack. And this only works when building MockK with Java 17.

**Comment by hantsy** [comment]
It seems a Kotlin-1.7 support merged into the master, not sure if it fixed this issue.

**Comment by pkgonan** [comment]
@Raibaz 
Hi.
Has this problem been fixed in Master?

**Comment by javiyt** [comment]
In my case is failing even with sealed classes returned by the mocked method, so the workaround to mock an implementation of the sealed class is not working, even when I'm returning the mock with that implementation.

**Comment by pkgonan** [comment]
@Raibaz 
Hi. When is the release date of 1.12.5 ?

**Comment by Raibaz** [comment]
I'm currently having issues publishing to oss.sonatype.org: https://issues.sonatype.org/browse/OSSRH-83030

As soon as this is resolved, I'll publish a new release.

**Comment by odin-delrio** [comment]
I updated my project to the 1.12.5 but still having the issue... (with JDK 17 and kotlin 1.7.10)

```
    java.lang.InstantiationError: com.example.MySealedClass
        at jdk.internal.reflect.GeneratedSerializationConstructorAccessor55.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:48)
        at io.mockk.proxy.jvm.ObjenesisInstantiator.instanceViaObjenesis(ObjenesisInstantiator.kt:75)
        at io.mockk.proxy.jvm.ObjenesisInstantiator.instance(ObjenesisInstantiator.kt:42)
        at io.mockk.impl.instantiation.JvmInstantiator$instantiate$2.invoke(JvmInstantiator.kt:16)
        at io.mockk.impl.instantiation.AbstractInstantiator.instantiateViaInstanceFactoryRegistry(AbstractInstantiator.kt:17)
        at io.mockk.impl.instantiation.JvmInstantiator.instantiate(JvmInstantiator.kt:15)
        at io.mockk.impl.recording.JvmSignatureValueGenerator$signatureValue$1.invoke(JvmSignatureValueGenerator.kt:42)
        at io.mockk.impl.instantiation.JvmAnyValueGenerator$anyValue$2.invoke(JvmAnyValueGenerator.kt:35)
        at io.mockk.impl.instantiation.AnyValueGenerator.anyValue(AnyValueGenerator.kt:34)
        at io.mockk.impl.instantiation.JvmAnyValueGenerator.anyValue(JvmAnyValueGenerator.kt:31)
        at io.mockk.impl.recording.JvmSignatureValueGenerator.signatureValue(JvmSignatureValueGenerator.kt:41)
        at io.mockk.impl.recording.states.RecordingState.matcher(RecordingState.kt:46)
        at io.mockk.impl.recording.CommonCallRecorder.matcher(CommonCallRecorder.kt:52)
```

**Comment by pkgonan** [comment]
Same here.

Environment
* JDK 17
* Kotlin 1.7.10
* Mockk 1.2.5

Error Log
```
LiveChatNameMessageTest > Invalid name should throw exception() FAILED
    org.opentest4j.AssertionFailedError: Unexpected exception type thrown ==> expected: <com.hpcnt.messagingplatform.exception.InvalidArgumentException> but was: <io.mockk.MockKException>
        at app//org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:65)
        at app//org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:37)
        at app//org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3082)
        at app//com.hpcnt.messagingplatform.livechatmessage.LiveChatNameMessageTest.Invalid name should throw exception(LiveChatNameMessageTest.kt:55)

        Caused by:
        io.mockk.MockKException: Can't instantiate proxy for class com.hpcnt.messagingplatform.message.Message
            at app//io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:64)
            at app//io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:29)
            at app//io.mockk.impl.instantiation.AbstractMockFactory.mockk(AbstractMockFactory.kt:59)
            at app//com.hpcnt.messagingplatform.livechatmessage.LiveChatNameMessageTest.Invalid name should throw exception(LiveChatNameMessageTest.kt:31)

            Caused by:
            io.mockk.proxy.MockKAgentException: Failed to subclass interface com.hpcnt.messagingplatform.message.Message
                at app//io.mockk.proxy.jvm.ProxyMaker.proxy(ProxyMaker.kt:38)
                at app//io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:34)
                ... 3 more

                Caused by:
                java.lang.IllegalArgumentException: Could not create type
                    at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:170)
                    at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:190)
                    at io.mockk.proxy.jvm.transformation.SubclassInstrumentation.subclass(SubclassInstrumentation.kt:51)
                    at io.mockk.proxy.jvm.ProxyMaker.subclass(ProxyMaker.kt:113)
                    at io.mockk.proxy.jvm.ProxyMaker.proxy(ProxyMaker.kt:35)
                    ... 4 more

                    Caused by:
                    java.lang.IllegalStateException: java.lang.IllegalStateException: Failed to invoke proxy for public abstract java.lang.Class net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup$MethodHandles$Lookup.defineClass(java.lang.Object,byte[]) throws java.lang.IllegalAccessException
                        at net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup.injectRaw(ClassInjector.java:1640)
                        at net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:118)
                        at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$UsingLookup.load(ClassLoadingStrategy.java:519)
                        at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101)
                        at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6166)
                        at io.mockk.proxy.jvm.transformation.SubclassInstrumentation.doInterceptedSubclassing(SubclassInstrumentation.kt:98)
                        at io.mockk.proxy.jvm.transformation.SubclassInstrumentation.access$doInterceptedSubclassing(SubclassInstrumentation.kt:21)
                        at io.mockk.proxy.jvm.transformation.SubclassInstrumentation$subclass$1.call(SubclassInstrumentation.kt:54)
                        at io.mockk.proxy.jvm.transformation.SubclassInstrumentation$subclass$1.call(SubclassInstrumentation.kt:21)
                        at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:168)
                        ... 8 more

                        Caused by:
                        java.lang.IllegalStateException: Failed to invoke proxy for public abstract java.lang.Class net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup$MethodHandles$Lookup.defineClass(java.lang.Object,byte[]) throws java.lang.IllegalAccessException
                            at net.bytebuddy.utility.dispatcher.JavaDispatcher$ProxiedInvocationHandler.invoke(JavaDispatcher.java:1173)
                            at jdk.proxy3/jdk.proxy3.$Proxy52.defineClass(Unknown Source)
                            at net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup.injectRaw(ClassInjector.java:1638)
                            ... 17 more

                            Caused by:
                            java.lang.IncompatibleClassChangeError: class com.hpcnt.messagingplatform.message.Message$Subclass12 cannot implement sealed interface com.hpcnt.messagingplatform.message.Message
                                at java.base/java.lang.ClassLoader.defineClass0(Native Method)
                                at java.base/java.lang.System$2.defineClass(System.java:2307)
                                at java.base/java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClass(MethodHandles.java:2439)
                                at java.base/java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClass(MethodHandles.java:2416)
                                at java.base/java.lang.invoke.MethodHandles$Lookup.defineClass(MethodHandles.java:1843)
                                at java.base/jdk.internal.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
                                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                                at java.base/java.lang.reflect.Method.invoke(Method.java:568)
                                at net.bytebuddy.utility.Invoker$Dispatcher.invoke(Unknown Source)
                                at net.bytebuddy.utility.dispatcher.JavaDispatcher$Dispatcher$ForNonStaticMethod.invoke(JavaDispatcher.java:1028)
                                at net.bytebuddy.utility.dispatcher.JavaDispatcher$ProxiedInvocationHandler.invoke(JavaDispatcher.java:1158)
                                ... 19 more
```

**Comment by hantsy** [comment]
I still encountered this issue with Kotlin 1.7.10/Java 17/Mockk 1.12.5, when `returns` a sealed class object in the mocking statement.

**Comment by aSemy** [comment]
@odin-delrio @pkgonan @hantsy Can you provide a minimal reproducer?

Here's the existing test, which passes, so there must be some difference... https://github.com/mockk/mockk/blob/3adc92e2c480c24fb6f1dcffd351510071a397ea/mockk/common/src/test/kotlin/io/mockk/it/SealedClassTest.kt

**Comment by knyttl** [comment]
For me 1.12.5 fixes the `every` issue, however, it creates a new one 🤦🏻‍♂️

🙏 see https://github.com/mockk/mockk/issues/868

**Comment by hantsy** [comment]
@aSemy Created a simple project to reproduce it. https://github.com/hantsy/mockk-issue832

**Comment by odin-delrio** [comment]
hey @aSemy I created a project recreating the issue
https://github.com/odin-delrio/mockk-issue-832

The key point is that the JVM target for the kotlin compilation options [must also be set to reproduce the issue](https://github.com/odin-delrio/mockk-issue-832/blob/main/build.gradle.kts#L30-L35) (I'm using a [build matrix for the tests](https://github.com/odin-delrio/mockk-issue-832/blob/main/.github/workflows/test.yml#L14)):

![image](https://user-images.githubusercontent.com/9112748/181551175-9e911d4e-dc54-47b9-b8d9-09bef152912f.png)
(The env var is set in the GH action when running the tests, getting the value from the testing matrix)


Here you have the link to the failing build when using JDK 17 https://github.com/odin-delrio/mockk-issue-832/runs/7561938775?check_suite_focus=true#step:4:428

![image](https://user-images.githubusercontent.com/9112748/181547634-1bedbce2-0189-4816-8e7e-e5b5c08f041a.png)


The same build with [JDK 11 succeeded](https://github.com/odin-delrio/mockk-issue-832/runs/7561938668?check_suite_focus=true).

**Comment by pkgonan** [comment]
@aSemy 
Hi.

You can find the error by running the test below.

Environment
* JDK 17
* Kotlin 1.7.10
* Mockk 1.2.5

Test Code
```
class MockkTest {

    @Test
    fun create(): Unit = runBlocking {
        val entity = getEntity()
    }

    private fun getEntity(): Entity = mockk(relaxed = true)

    sealed interface Entity {
        fun getType(): String
    }

    class AEntity private constructor(
        private val height: Int
    ): Entity {

        companion object {
            operator fun invoke(height: Int): Entity {
                return AEntity(height)
            }
        }

        override fun getType() = "A"
    }

    class BEntity private constructor(
        private val name: String
    ): Entity {

        companion object {
            operator fun invoke(name: String): Entity {
                return BEntity(name)
            }
        }

        override fun getType() = "B"
    }
}
```

Error Log
```

io.mockk.MockKException: Can't instantiate proxy for class com.hpcnt.messagingplatform.test.MockkTest$Entity

	at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:64)
	at io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:29)
	at io.mockk.impl.instantiation.AbstractMockFactory.mockk(AbstractMockFactory.kt:59)
	at com.hpcnt.messagingplatform.test.MockkTest.getEntity(MockkTest.kt:71)
	at com.hpcnt.messagingplatform.test.MockkTest.access$getEntity(MockkTest.kt:10)
	at com.hpcnt.messagingplatform.test.MockkTest$create$1.invokeSuspend(MockkTest.kt:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.hpcnt.messagingplatform.test.MockkTest.create(MockkTest.kt:13)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: io.mockk.proxy.MockKAgentException: Failed to subclass interface com.hpcnt.messagingplatform.test.MockkTest$Entity
	at io.mockk.proxy.jvm.ProxyMaker.proxy(ProxyMaker.kt:38)
	at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:34)
	... 83 more
Caused by: java.lang.IllegalArgumentException: Could not create type
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:170)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:190)
	at io.mockk.proxy.jvm.transformation.SubclassInstrumentation.subclass(SubclassInstrumentation.kt:51)
	at io.mockk.proxy.jvm.ProxyMaker.subclass(ProxyMaker.kt:113)
	at io.mockk.proxy.jvm.ProxyMaker.proxy(ProxyMaker.kt:35)
	... 84 more
Caused by: java.lang.IllegalStateException: java.lang.IllegalStateException: Failed to invoke proxy for public abstract java.lang.Class net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup$MethodHandles$Lookup.defineClass(java.lang.Object,byte[]) throws java.lang.IllegalAccessException
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup.injectRaw(ClassInjector.java:1640)
	at net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:118)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$UsingLookup.load(ClassLoadingStrategy.java:519)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6166)
	at io.mockk.proxy.jvm.transformation.SubclassInstrumentation.doInterceptedSubclassing(SubclassInstrumentation.kt:98)
	at io.mockk.proxy.jvm.transformation.SubclassInstrumentation.access$doInterceptedSubclassing(SubclassInstrumentation.kt:21)
	at io.mockk.proxy.jvm.transformation.SubclassInstrumentation$subclass$1.call(SubclassInstrumentation.kt:54)
	at io.mockk.proxy.jvm.transformation.SubclassInstrumentation$subclass$1.call(SubclassInstrumentation.kt:21)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:168)
	... 88 more
Caused by: java.lang.IllegalStateException: Failed to invoke proxy for public abstract java.lang.Class net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup$MethodHandles$Lookup.defineClass(java.lang.Object,byte[]) throws java.lang.IllegalAccessException
	at net.bytebuddy.utility.dispatcher.JavaDispatcher$ProxiedInvocationHandler.invoke(JavaDispatcher.java:1173)
	at jdk.proxy2/jdk.proxy2.$Proxy47.defineClass(Unknown Source)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup.injectRaw(ClassInjector.java:1638)
	... 97 more
Caused by: java.lang.IncompatibleClassChangeError: class com.hpcnt.messagingplatform.test.MockkTest$Entity$Subclass0 cannot implement sealed interface com.hpcnt.messagingplatform.test.MockkTest$Entity
	at java.base/java.lang.ClassLoader.defineClass0(Native Method)
	at java.base/java.lang.System$2.defineClass(System.java:2307)
	at java.base/java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClass(MethodHandles.java:2439)
	at java.base/java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClass(MethodHandles.java:2416)
	at java.base/java.lang.invoke.MethodHandles$Lookup.defineClass(MethodHandles.java:1843)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.bytebuddy.utility.Invoker$Dispatcher.invoke(Unknown Source)
	at net.bytebuddy.utility.dispatcher.JavaDispatcher$Dispatcher$ForNonStaticMethod.invoke(JavaDispatcher.java:1028)
	at net.bytebuddy.utility.dispatcher.JavaDispatcher$ProxiedInvocationHandler.invoke(JavaDispatcher.java:1158)
	... 99 more
```

**Comment by sonwig** [comment]
> @odin-delrio @pkgonan @hantsy Can you provide a minimal reproducer?
> 
> Here's the existing test, which passes on jdk17 & Kotlin 1.7, so there must be some difference... https://github.com/mockk/mockk/blob/3adc92e2c480c24fb6f1dcffd351510071a397ea/mockk/common/src/test/kotlin/io/mockk/it/SealedClassTest.kt

This test fails for me on jdk17, Kotlin 1.7 and mockk 1.12.5: java.lang.InstantiationError: testutils.SealedClassTest$Companion$Node

**Comment by pkgonan** [comment]
@aSemy 
Hi.

Is there any update?

**Comment by aSemy** [comment]
@pkgonan Not from me. I can try and have a go at fixing this, but I can't reproduce it. The test works on my machine and on the GitHub build. I don't doubt there's a problem, but without a reproduction I don't know where to begin.

Can those who have issues try cloning the project and running the tests? `./gradlew test`

(btw it's nice to have a ping but I don't have any special insight into MockK, I've just made a few pull requests 🙂)

**Comment by ThanksForAllTheFish** [comment]
I updated my sample to mockk 1.12.5 and kotlin 1.7.10 and still have this issue: https://github.com/ThanksForAllTheFish/mockk832 just so there is another reproducer around

**Comment by sonwig** [comment]
@aSemy

I have cloned the project and the reason it works is because it is using Java 8 and not Java 17. 
https://github.com/mockk/mockk/blob/master/build.gradle
https://github.com/mockk/mockk/blob/master/mockk/common/build.gradle.kts

**Comment by aSemy** [comment]
Thanks for providing more information! I've managed to reproduce it in the project tests in my refactoring PR #855.

The sealed class tests fail on 17 and 18, but pass on 11, as reported: https://github.com/mockk/mockk/actions/runs/2827760564 This is a step towards a solution...

For the sake of finishing the PR, I'll disable the tests, then the problem can be investigated properly.

**Comment by aSemy** [comment]
I've done research into this and I believe the problem is happening in `ObjensesisInstantiator`

https://github.com/mockk/mockk/blob/6c571a651e74e66fe364b802a83849bfc7d6e802/modules/mockk-agent/src/jvmMain/kotlin/io/mockk/proxy/jvm/ObjenesisInstantiator.kt#L23-L43

Basically this tries to create a dummy, but valid, instance of a class. MockK can then keep track of this dummy instance, and where it is used. For primitives this is simple, MockK just creates a random primitive. For classes it's a little more complicated, as MockK has to create an instance that conforms to that class' requirements. Normally that's okay, especially if the class is abstract or open. However, a sealed class looks like it's abstract and open.... except for it's not.

So there are two problems:

1. MockK can't tell if a class is sealed. In `ObjensesisInstantiator` a Java `Class<T>` is used, not a `KClass<T>`, and so finding out if the class is sealed is more difficult
2. How can MockK create a dummy instance of a sealed class? It needs to find the valid subclasses are available. If it can do that, then it can pick some random (non-sealed) subclass, and generate an instance in the usual manner.

I tried refactoring MockK to accept a `KClass<T>`, and so gain access to the `isSealed` and `sealedSubclasses` methods from Kotlin Reflect, but this requires a *lot* of refactoring, and this broke many other parts of the code. 

```kotlin
override fun <T : Any> instance(cls: KClass<T>): T? {
    return when {
        cls.java == Any::class.java -> {
            @Suppress("UNCHECKED_CAST")
            Any() as T
        }

        cls.isSealed -> {
            cls.sealedSubclasses.firstNotNullOfOrNull { subCls ->
                runCatching { instance(subCls) }.getOrNull()
            } ?: error("$cls has no non-sealed subclasses")
        }

        !Modifier.isFinal(cls.java.modifiers) -> {
            try {
                instantiateViaProxy(cls.java)
            } catch (ex: Exception) {
                log.trace(
                    ex,
                    "Failed to instantiate via proxy $cls (${ex::class.simpleName} ${ex.message}), doing objenesis instantiation"
                )
                instanceViaObjenesis(cls.java)
            }

        }

        else -> instanceViaObjenesis(cls.java)
    }
}
```

This problem isn't impossible to overcome, but it's not a quick fix. I'm sharing my work here, so hopefully someone else can take a look and either find another fix, or find something I missed.

**Comment by Or4ng3** [comment]
> MockK can't tell if a class is sealed. In ObjensesisInstantiator a Java Class<T> is used, not a KClass<T>, and so finding out if the class is sealed is more difficult

Can you tell, why `java.lang.Class<T>` is not enought in this case? 

From my understanding, java.lang.Class also has this data (.isSealed() method and .getPermittedSubclasses()). And starting from Kotlin 1.7, when using 17+ target bytecode level, kotlin generates classes that are also sealed in JVM terms. 
For older bytecode versions current issue is not applicable, so doesn't matter if JVM says that class is not sealed

**Comment by aSemy** [comment]
> Can you tell, why `java.lang.Class<T>` is not enought in this case?
> 
> From my understanding, java.lang.Class also has this data (.isSealed() method and .getPermittedSubclasses()). And starting from Kotlin 1.7, when using 17+ target bytecode level, kotlin generates classes that are also sealed in JVM terms. For older bytecode versions current issue is not applicable, so doesn't matter if JVM says that class is not sealed

`Class.isSealed()` is only available on JVM 17+. I tried using it #915, but then MockK won't compile on JVM 11: https://github.com/mockk/mockk/runs/8178643128?check_suite_focus=true#step:6:72

**Comment by stuebingerb** [comment]
Two ideas, maybe one of them helps.

1. We should be able to get the `KClass` from the existing `Class` using the `.kotlin` extension: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.jvm/java.lang.-class/
2. We could call `isSealed` and `getPermittedSubclasses` using reflection, something along the lines of
    ```
    fun Class<*>.isSealedSafe() =
        javaClass.methods.firstOrNull { it.name == "isSealed" }?.invoke(this) ?: false
    fun Class<*>.getPermittedSubclassesSafe() =
        javaClass.methods.firstOrNull { it.name == "getPermittedSubclasses" }?.let { it.invoke(this) as Array<Class<*>> } ?: emptyArray()
    ```

**Comment by ThanksForAllTheFish** [comment]
> Class.isSealed() is only available on JVM 17+. I tried using it https://github.com/mockk/mockk/pull/915, but then MockK won't compile on JVM 11: https://github.com/mockk/mockk/runs/8178643128?check_suite_focus=true#step:6:72

Could you think of a switch specific to the version? something like https://github.com/apache/commons-lang/blob/master/src/test/java/org/apache/commons/lang3/reflect/FieldUtilsTest.java#L1020:

```
if (current version > 17) {
  use native java 17 sealed check
} else {
  current code
}
```

it is not pretty, but should be a smaller change. Just "dumping" ideas if they might help

**Comment by NatsuOnFire** [comment]
Since Java 9, you can use Runtime.version()
```kotlin
println(Runtime.version()) // 17.0.1+12-LTS
println(Runtime.version().feature()) // 17
```

And before Java 9 : 
```kotlin
println(System.getProperty("java.specification.version")) // 17
```

**Comment by aSemy** [comment]
Great ideas, would you be able to give them a go?

1. fork the MockK repo
2. make some changes
3. make a PR against the MockK repo, which will automatically trigger the tests for all JVM versions
4. check the test results 
5. gain eternal glory in the MockK patch notes :)

**Comment by stuebingerb** [comment]
Tried but the test workflows are not so automated for first-time contributors 😉 
https://github.com/mockk/mockk/pull/916

**Comment by aSemy** [comment]
> Tried but the test workflows are not so automated for first-time contributors 😉 #916

Good point! I forgot. As a workaround you can create a PR in your own fork, from the branch against master.

**Comment by sishbi** [comment]
Hey, I see from https://github.com/stuebingerb/mockk/pull/1 that all of the tests now pass, is this good to merge and be included in a new MockK release?  My projects are waiting to upgrade to Kotlin 1.7 due to this mockk failure.
Thanks!

**Comment by hantsy** [comment]
I am also waiting a new release to upgrade my project to Kotlin 1.7.

**Comment by raycoarana** [comment]
But the code has not been merged in the main repo, right? The new release do not include the fixing code.

**Comment by seljabali** [comment]
https://github.com/mockk/mockk/pull/916 attempts to fix the issue & hasn't been merged yet.

**Comment by sishbi** [comment]
> #916 attempts to fix the issue & hasn't been merged yet.

What's holding up the merge?  Can it be included in `1.12.8` also ?

**Comment by hantsy** [comment]
Updated to 1.12.8, still failed https://github.com/hantsy/mockk-issue832/actions/runs/3065819014/jobs/4950308126#step:4:42
I used `mockk-jvm` instead.

**Comment by seljabali** [comment]
@Raibaz may we have a new release now that https://github.com/mockk/mockk/pull/916 got merged? Thanks in advance!

**Comment by Raibaz** [comment]
Done, v1.13.2 is out :)

**Comment by cliffred** [comment]
1.13.2 only partly solves the issue:

```kotlin
// given the following sealed class
sealed class Foo
class FooSub : Foo()

// and the following class with a method that has function with a sealed class as parameter
class Bar {
    fun fooParam(foo: Foo): Int = 42
}

// then the following now works
val foo : Foo = mockk() // Fixed since 1.13.2

// but when using any() where a sealed class is expected the issue still persists
val bar: Bar = mockk()
every { bar.fooParam(any()) } returns 1 // throws InstantiationError
```

**Comment by chrissearle** [comment]
@cliffred that matches what I am seeing locally with 1.13.2.

I wonder if this should be re-opened or a more specific issue raised?

**Comment by petitcl** [comment]
For those still looking at this issue like me, it was fixed in [this [PR](url)](https://github.com/mockk/mockk/pull/939), which was released in `1.13.3`.

**Comment by sud007** [comment]
Sealed class issue got fixed for me with 1.13.2
