### ISSUE TITLE
Bug: mockkStatic/mockObject raise exception for Android or generic classes

### ISSUE THREAD

**Issue by QiBaobin** [mockk/mockk#86]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Expected Behavior

mockkObject/mockStatic work without exceptions on Android classes or generic classes.

### Current Behavior

KotlinNullPointException

### Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.8.1
* OS: macOS 10.13.4
* Kotlin version: 1.2.41
* JDK version: 1.8
* Type of test: unit test

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
kotlin.KotlinNullPointerException
	at io.mockk.impl.stub.MockKStub$childMockK$$inlined$synchronized$lambda$1$1.invoke(MockKStub.kt:119)
	at io.mockk.impl.stub.MockKStub$childMockK$$inlined$synchronized$lambda$1$1.invoke(MockKStub.kt:8)
	at io.mockk.impl.InternalPlatform.customComputeIfAbsent(InternalPlatform.kt:44)
	at io.mockk.impl.stub.MockKStub$childMockK$$inlined$synchronized$lambda$1.invoke(MockKStub.kt:118)
	at io.mockk.impl.recording.CommonCallRecorder.safeExec(CommonCallRecorder.kt:66)
	at io.mockk.impl.log.SafeLog.exec(SafeLog.kt:10)
	at io.mockk.impl.stub.MockKStub.childMockK(MockKStub.kt:117)
	at io.mockk.impl.recording.PermanentMocker.permamentize(PermanentMocker.kt:48)
	at io.mockk.impl.recording.PermanentMocker.mock(PermanentMocker.kt:24)
	at io.mockk.impl.recording.states.RecordingState.mockPermanently(RecordingState.kt:115)
	at io.mockk.impl.recording.states.RecordingState.round(RecordingState.kt:32)
	at io.mockk.impl.recording.CommonCallRecorder.round(CommonCallRecorder.kt:45)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:47)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:25)
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
    @Test
    fun objectExtensionFunction() {
        mockkObject(Obj)
        every {
            Obj.testIntent()
        } returns mockk()
    }


object Obj {
    fun testIntent(): List<Int> = TODO()
// OR fun testIntent(): android.content.Intent = TODO()
}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by oleksiyp** [comment]
Please try version 1.8.2. I fixed few bugs there

**Comment by QiBaobin** [comment]
Thanks for the quick reply, I just tried and 1.8.2 didn't fix the issue.

**Comment by QiBaobin** [comment]
Thanks, verified that it's fixed in 1.8.3.
